OPENAI_API_BASE = "XXXXXXXXXX"
MODEL_NAME = "XXXXXXXXXX"
OPENAI_API_KEY = "XXXXXXXXXX"

Qwen_PATH = "XXXXXXXXXX"
ChatGLM_PATH = "XXXXXXXXXX"
BGEModel_PATH = "XXXXXXXXXX"

CharacterLLM_DATA_PATH = "XXXXXXXXXX"
